'use client';
import {useParams} from 'next/navigation';
import {useQuery} from '@tanstack/react-query';
import Link from 'next/link';
import apiClient from '@/services/apiClient';
import {useAuth} from '@/contexts/AuthContext';
import {useJcAccess,errorMessage,buttonClass} from '@/components/jobChallan/useJcAccess';
interface Item {id:number;item_id:number;item_name:string;description:string;quantity:number;unit:string;remarks:string;}
export default function Page(){const {id}=useParams(),{user}=useAuth(),{can,loading}=useJcAccess();const query=useQuery({queryKey:['gatepassDetail',user?.db,id],enabled:can('gatepasses','view'),queryFn:async()=>(await apiClient.get('/gatepass/'+id)).data.data});if(loading || query.isLoading)return <p className="p-6">Loading...</p>;if(!can('gatepasses','view'))return <p className="p-6">Access denied.</p>;if(query.isError)return <p role="alert">{errorMessage(query.error)}</p>;const g=query.data?.gatepass;if(!g)return null;return <main className="max-w-6xl mx-auto p-6 space-y-5"><div className="flex gap-4"><Link href="/dashboard/gatepass">Back</Link>{can('gatepasses','edit') && <Link className={buttonClass} href={`/dashboard/gatepass/${id}/edit`}>Edit</Link>}{can('gatepasses','gatepasspdf') && <Link className={buttonClass} href={`/dashboard/gatepass/${id}/pdf`}>Print / PDF</Link>}</div><section className="bg-white rounded-xl border p-6 space-y-4"><h1 className="text-2xl font-bold">Gate Pass {g.gatepass_no}</h1><div className="grid grid-cols-2 md:grid-cols-3 gap-4">{[['Type',g.gatepass_type],['Date',g.date],['Company',g.vendor_name || g.company_name],['Vehicle',g.vehicle_no],['Return Date',g.return_date],['Status',g.status],['Job Challans',g.jcs.map((jc:{challan_no:string})=>jc.challan_no).join(', ')],['Remarks',g.remarks]].map(([title,value])=><div key={title}><span className="text-slate-500 text-sm">{title}</span><p className="whitespace-pre-line">{value || '-'}</p></div>)}</div><table className="w-full text-sm"><thead><tr>{['Item Code','Item / Description','Quantity','Unit','Remarks'].map(h=><th key={h} className="p-2 text-left">{h}</th>)}</tr></thead><tbody>{g.items.map((item:Item)=><tr key={item.id} className="border-t"><td className="p-2">{item.item_id}</td><td className="p-2 whitespace-pre-line"><b>{item.item_name}</b><p>{item.description}</p></td><td className="p-2">{item.quantity}</td><td className="p-2">{item.unit}</td><td className="p-2">{item.remarks}</td></tr>)}</tbody></table></section></main>;}
